Repository MUMU-For-Youth/MUMU_Backend, pull requests merged in 2025-04, with the labels that each got.

#7 카카오 로그인 백엔드 구현(연동 전)
  .gitignore
  build.gradle
  src/main/java/com/mumu/mumu/controller/KakaoLoginController.java
  src/main/java/com/mumu/mumu/controller/KakaoLoginPageController.java
  src/main/java/com/mumu/mumu/dto/KakaoTokenResponseDto.java
  src/main/java/com/mumu/mumu/dto/KakaoUserInfoResponseDto.java
  src/main/java/com/mumu/mumu/service/KakaoService.java
  src/main/resources/application.properties
  src/main/resources/static/kakao_login_button.png
  src/main/resources/templates/login.html
Labels: feat, fix

#9 [CHORE] Insert user's tokens into RDS
  build.gradle
  src/main/java/com/mumu/mumu/controller/KakaoLoginController.java
  src/main/java/com/mumu/mumu/domain/Member.java
  src/main/java/com/mumu/mumu/repository/MemberRepository.java
  src/main/java/com/mumu/mumu/service/KakaoService.java
Labels: chore

#13 [Feat] Setting Entities about edu&space(IS RELATED TO #11)
  src/main/java/com/mumu/mumu/controller/MapMarkerController.java
  src/main/java/com/mumu/mumu/domain/Edu.java
  src/main/java/com/mumu/mumu/domain/Space.java
  src/main/java/com/mumu/mumu/dto/EduMarkerDTO.java
  src/main/java/com/mumu/mumu/dto/SpaceMarkerDTO.java
  src/main/java/com/mumu/mumu/repository/EducationRepository.java
  src/main/java/com/mumu/mumu/repository/SpaceRepository.java
  src/main/java/com/mumu/mumu/service/MapMarkerService.java
Labels: feat

#15 [Fix] Setting Entities about edu&space(IS RELATED TO #11)
  src/main/java/com/mumu/mumu/domain/Edu.java
  src/main/java/com/mumu/mumu/domain/Space.java
Labels: fix

#16 [Fix] 엔티티 컬럼 이름 수정
  src/main/java/com/mumu/mumu/domain/Edu.java
  src/main/java/com/mumu/mumu/domain/Member.java
  src/main/java/com/mumu/mumu/domain/Space.java
Labels: fix

#17 [Feat] 무료교육 리스트 조회 구현
  src/main/java/com/mumu/mumu/controller/EduListController.java
  src/main/java/com/mumu/mumu/dto/EduListResponseDto.java
  src/main/java/com/mumu/mumu/repository/EduListRepository.java
  src/main/java/com/mumu/mumu/service/EduListService.java
  src/main/java/com/mumu/mumu/service/EduListServiceImpl.java
  src/main/java/com/mumu/mumu/specification/EduListSpecification.java
Labels: feat

#19 [Feat] Map Marker
  build.gradle
  src/main/java/com/mumu/mumu/controller/MapMarkerController.java
  src/main/java/com/mumu/mumu/dto/EduMarkerDTO.java
  src/main/java/com/mumu/mumu/dto/SpaceMarkerDTO.java
  src/main/java/com/mumu/mumu/exception/GlobalExceptionHandler.java
  src/main/java/com/mumu/mumu/repository/EducationRepository.java
  src/main/java/com/mumu/mumu/repository/SpaceRepository.java
  src/main/java/com/mumu/mumu/service/MapMarkerService.java
  src/main/java/com/mumu/mumu/specification/EduSpecification.java
  src/main/java/com/mumu/mumu/specification/SpaceSpecification.java
Labels: feat

#22 [Feat] POST functions Completed(IS RELATED TO #20)
  src/main/java/com/mumu/mumu/controller/BookmarkController.java
  src/main/java/com/mumu/mumu/domain/EduBookmark.java
  src/main/java/com/mumu/mumu/domain/SpaceBookmark.java
  src/main/java/com/mumu/mumu/dto/EduBookmarkDTO.java
  src/main/java/com/mumu/mumu/dto/SpaceBookmarkDTO.java
  src/main/java/com/mumu/mumu/repository/EduBookmarkRepository.java
  src/main/java/com/mumu/mumu/repository/MemberRepository.java
  src/main/java/com/mumu/mumu/repository/SpaceBookmarkRepository.java
  src/main/java/com/mumu/mumu/service/BookmarkService.java
Labels: feat

#26 [Feat] GET functions Completed(Resolves #20)
  src/main/java/com/mumu/mumu/controller/BookmarkController.java
  src/main/java/com/mumu/mumu/dto/EduBookmarkResponseDTO.java
  src/main/java/com/mumu/mumu/dto/SpaceBookmarkResponseDTO.java
  src/main/java/com/mumu/mumu/repository/EduBookmarkRepository.java
  src/main/java/com/mumu/mumu/repository/SpaceBookmarkRepository.java
  src/main/java/com/mumu/mumu/repository/SpaceRepository.java
  src/main/java/com/mumu/mumu/service/BookmarkService.java
  src/main/java/com/mumu/mumu/specification/EduSpecification.java
  src/main/java/com/mumu/mumu/specification/SpaceSpecification.java
Labels: feat

#27 [CHORE]Docker related files for CI/CD
  Dockerfile
  docker-compose.yml
  src/main/java/com/mumu/mumu/exception/GlobalExceptionHandler.java
  src/main/resources/logback-spring.xml
Labels: chore

#25 [Feat] 공간 전체/상세 조회 기능 구현
  src/main/java/com/mumu/mumu/controller/SpaceListController.java
  src/main/java/com/mumu/mumu/dto/SpaceDetailResponseDto.java
  src/main/java/com/mumu/mumu/dto/SpaceListResponseDto.java
  src/main/java/com/mumu/mumu/repository/SpaceRepository.java
  src/main/java/com/mumu/mumu/service/SpaceListService.java
  src/main/java/com/mumu/mumu/service/SpaceListServiceImpl.java
  src/main/java/com/mumu/mumu/specification/SpaceListSpecification.java
Labels: feat

#29 [Feat] Multiple Filtering w/ ,
  src/main/java/com/mumu/mumu/controller/EduListController.java
  src/main/java/com/mumu/mumu/controller/SpaceListController.java
  src/main/java/com/mumu/mumu/service/EduListService.java
  src/main/java/com/mumu/mumu/service/EduListServiceImpl.java
  src/main/java/com/mumu/mumu/service/SpaceListService.java
  src/main/java/com/mumu/mumu/service/SpaceListServiceImpl.java
Labels: feat

#33 [Feat] bookmarked
  src/main/java/com/mumu/mumu/controller/EduListController.java
  src/main/java/com/mumu/mumu/controller/SpaceListController.java
  src/main/java/com/mumu/mumu/dto/EduDetailResponseDto.java
  src/main/java/com/mumu/mumu/dto/EduListResponseDto.java
  src/main/java/com/mumu/mumu/dto/SpaceDetailResponseDto.java
  src/main/java/com/mumu/mumu/dto/SpaceListResponseDto.java
  src/main/java/com/mumu/mumu/service/EduListService.java
  src/main/java/com/mumu/mumu/service/EduListServiceImpl.java
  src/main/java/com/mumu/mumu/service/SpaceListService.java
  src/main/java/com/mumu/mumu/service/SpaceListServiceImpl.java
Labels: feat

#34 [Fix] 공간 상세 조회 response 수정
  src/main/java/com/mumu/mumu/dto/SpaceDetailResponseDto.java
Labels: fix
