Repository MUMU-For-Youth/MUMU_Backend, pull requests merged in 2025-05, with the labels that each got.

#32 [Fix] 교육 상세 조회 response 수정
  src/main/java/com/mumu/mumu/dto/EduDetailResponseDto.java
Labels: fix

#35 [Fix] 공간 리스트 조회 response 이미지 추가
  src/main/java/com/mumu/mumu/dto/SpaceListResponseDto.java
Labels: fix

#36 [Fix] 교육 리스트 조회 response 이미지 추가
  src/main/java/com/mumu/mumu/dto/EduListResponseDto.java
Labels: fix

#37 [Fix] 교육 리스트 조회 DTO 수정
  src/main/java/com/mumu/mumu/dto/EduListResponseDto.java
Labels: fix

#38 [Fix] spaceRegion -> region 수정
  src/main/java/com/mumu/mumu/service/SpaceListServiceImpl.java
Labels: fix

#39 [Fix] eduAddress 속성 eduRegion으로 변경
  src/main/java/com/mumu/mumu/specification/EduListSpecification.java
Labels: fix

#40 [Feat] 카카오 로그인 api 수정
  src/main/java/com/mumu/mumu/controller/AuthController.java
  src/main/java/com/mumu/mumu/controller/KakaoLoginController.java
  src/main/java/com/mumu/mumu/controller/KakaoLoginPageController.java
  src/main/java/com/mumu/mumu/service/KakaoService.java
Labels: feat

#42 [CHORE] changing front url2
  src/main/java/com/mumu/mumu/config/WebConfig.java
Labels: chore

#43 [CHORE] changing front url3
  src/main/java/com/mumu/mumu/config/WebConfig.java
Labels: chore

#44 [CHORE] Setting mumu domain
  Dockerfile
  nginx.conf
  src/main/java/com/mumu/mumu/config/WebConfig.java
  start.sh
Labels: chore

#46 [CHORE] Setting mumu domain as https2
  docker-compose.yml
Labels: chore

#47 [CHORE] allow localhost:3000 for dev
  src/main/java/com/mumu/mumu/config/WebConfig.java
Labels: chore

#57 reset
  src/main/java/com/mumu/mumu/MumuApplication.java
  src/main/java/com/mumu/mumu/dto/EduBookmarkResponseDTO.java
  src/main/java/com/mumu/mumu/dto/EduDetailResponseDto.java
  src/main/java/com/mumu/mumu/dto/EduListResponseDto.java
  src/main/java/com/mumu/mumu/dto/EduMarkerDTO.java
  src/main/java/com/mumu/mumu/dto/KakaoTokenResponseDto.java
  src/main/java/com/mumu/mumu/dto/KakaoUserInfoResponseDto.java
  src/main/java/com/mumu/mumu/dto/SpaceBookmarkDTO.java
  src/main/java/com/mumu/mumu/dto/SpaceDetailResponseDto.java
  src/main/java/com/mumu/mumu/dto/SpaceListResponseDto.java
  src/main/java/com/mumu/mumu/repository/EduListRepository.java
  src/main/java/com/mumu/mumu/repository/EducationRepository.java
  src/main/java/com/mumu/mumu/repository/MemberRepository.java
  src/main/java/com/mumu/mumu/repository/SpaceBookmarkRepository.java
  src/main/java/com/mumu/mumu/repository/SpaceRepository.java
  src/main/java/com/mumu/mumu/service/BookmarkService.java
  src/main/java/com/mumu/mumu/service/EduListService.java
  src/main/java/com/mumu/mumu/service/EduListServiceImpl.java
  src/main/java/com/mumu/mumu/service/KakaoService.java
  src/main/java/com/mumu/mumu/service/MapMarkerService.java
  src/main/java/com/mumu/mumu/service/SpaceListService.java
  src/main/java/com/mumu/mumu/service/SpaceListServiceImpl.java
  src/main/java/com/mumu/mumu/specification/EduListSpecification.java
  src/main/java/com/mumu/mumu/specification/SpaceListSpecification.java
Labels: bug

#58 [Fix] 프론트 redirect uri 삭제
  src/main/java/com/mumu/mumu/controller/KakaoLoginController.java
Labels: fix

#60 [Feat] 로그아웃 구현
  src/main/java/com/mumu/mumu/controller/KakaoLoginController.java
  src/main/java/com/mumu/mumu/service/KakaoService.java
Labels: feat

#61 [ Fix] 카카오 로그인 리디렉션 처리 및 콜백 엔드포인트 구현
  src/main/java/com/mumu/mumu/controller/KakaoLoginController.java
Labels: fix

#62 [Test] 프론트 로컬 서버로 로그인 연결
  src/main/java/com/mumu/mumu/controller/KakaoLoginController.java
Labels: test

#63 [Fix] 액세스 토큰 발급 시 redirect uri 설정
  src/main/java/com/mumu/mumu/controller/KakaoLoginController.java
  src/main/java/com/mumu/mumu/service/KakaoService.java
Labels: fix

#64 [Fix] 백엔드->카카오 /auth/kakao/callback request 수정
  src/main/java/com/mumu/mumu/service/KakaoService.java
Labels: fix

#65 [Fix] /auth/kakao/callback POST -> GET 변경
  src/main/java/com/mumu/mumu/controller/KakaoLoginController.java
Labels: fix

#66 [Fix] /auth/kakao/callback request 형식 변경
  src/main/java/com/mumu/mumu/service/KakaoService.java
Labels: fix

#67 [Fix] redirect uri 통일
  src/main/java/com/mumu/mumu/service/KakaoService.java
Labels: fix

#68 [Del] redirect uri encoding 삭제
  src/main/java/com/mumu/mumu/controller/KakaoLoginController.java
  src/main/java/com/mumu/mumu/service/KakaoService.java
Labels: fix

#70 [Fix] 로그인 기능 프론트 배포 페이지로 변경
  src/main/java/com/mumu/mumu/controller/KakaoLoginController.java
Labels: fix
